basePath: /
definitions:
  custom.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  models.CreateRepairRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    required:
    - email
    - firstName
    - lastName
    type: object
  models.GetRepairResponse:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  models.GetRepairsResponse:
    properties:
      repairs:
        items:
          $ref: '#/definitions/models.Repair'
        type: array
    type: object
  models.Repair:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
info:
  contact: {}
  title: Car Service
  version: "1.0"
paths:
  /v1/repairs:
    get:
      consumes:
      - application/json
      description: GetRepairs
      operationId: GetRepairs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetRepairsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
      summary: Get All Repairs
      tags:
      - Repairs
    post:
      consumes:
      - application/json
      description: CreateRepair
      operationId: RepairCreate
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateRepairRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetRepairResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
      summary: Create Repair
      tags:
      - Repairs
  /v1/repairs/{repairId}:
    delete:
      consumes:
      - application/json
      description: DeleteRepair
      operationId: DeleteRepair
      parameters:
      - description: repairId
        in: path
        name: repairId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
      summary: Delete repair by repairId
      tags:
      - Repairs
    get:
      consumes:
      - application/json
      description: GetRepair
      operationId: GetRepair
      parameters:
      - description: repairId
        in: path
        name: repairId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetRepairResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/custom.ErrorResponse'
      summary: Get Repair by repairId
      tags:
      - Repairs
schemes:
- http
swagger: "2.0"
